import Head from 'next/head';
import Link from 'next/link';
import { IndexWrapper, TextWrapper, Letters, LetterA, LetterC, Line1, Line2 } from "../styles/indexStyles";
import Image from 'next/image';
import logoind from "../public/images/LogoAC.png";
import { motion } from 'framer-motion';
import {pageAnimation, letterA, letterC, avocatAnim, avocat2Anim, lineIndex} from "../styles/animations";

export default function Home() {
  return (
    <>
      <motion.div
        variants={pageAnimation}
        exit="exit"
        initial="hidden"
        animate="show"
        >
        <Head>
          <title>Adèle CARLES</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <IndexWrapper>
            <Link className="linkInd" href={"/missions"}>
              <Letters>
                <LetterA variants={letterA}>A</LetterA>
                <LetterC variants={letterC}>C</LetterC>
                <motion.h1 variants={avocatAnim}>AVOCAT</motion.h1>
              </Letters>
              {/* <Image className="imgInd" src={logoind} alt="logo" /> */}
            </Link>
            <TextWrapper className="textInd">
              <motion.h1 variants={avocat2Anim}>AVOCAT AU BARREAU DE BORDEAUX</motion.h1>
            </TextWrapper>
            <Line1 variants={lineIndex}/>
            <Line2 variants={lineIndex}/>
          </IndexWrapper>
        </main>
      </motion.div>
    </>
  )
}
