import Head from 'next/head';
import Link from 'next/link';
import { Title, IndexWrapper } from "../styles/indexStyles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Adèle CARLES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <IndexWrapper>
          <Title>
            <h1>Hello you</h1>
          </Title>
        </IndexWrapper>
      </main>
    </>
  )
}
